package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val SandalBackgroundLight = Color(0xFFFAF9F5)
val SandalSurfaceLight = Color(0xFFFFFFFF)
val SandalPrimaryLight = Color(0xFF8B6C5C) 
val SandalOnPrimaryLight = Color(0xFFFFFFFF)
val SandalPrimaryContainerLight = Color(0xFFF1E6DA)
val SandalOnPrimaryContainerLight = Color(0xFF3E2D27)
val SandalSecondaryLight = Color(0xFF6B7280)
val SandalSecondaryContainerLight = Color(0xFFE5E7EB)
val SandalOnSecondaryContainerLight = Color(0xFF1F2937)
val SandalSurfaceVariantLight = Color(0xFFF4F0EA)
val SandalOnSurfaceVariantLight = Color(0xFF5A534E)
val SandalTextLight = Color(0xFF2C2825)
val SandalErrorLight = Color(0xFFB3595C)
val SandalErrorContainerLight = Color(0xFFF9DEDC)

val SandalBackgroundDark = Color(0xFF1E1C1A)
val SandalSurfaceDark = Color(0xFF262422)
val SandalPrimaryDark = Color(0xFFD6BAAA)
val SandalOnPrimaryDark = Color(0xFF3A2821)
val SandalPrimaryContainerDark = Color(0xFF543E34)
val SandalOnPrimaryContainerDark = Color(0xFFF1E6DA)
val SandalSecondaryDark = Color(0xFFA1A1AA)
val SandalSecondaryContainerDark = Color(0xFF374151)
val SandalOnSecondaryContainerDark = Color(0xFFE5E7EB)
val SandalSurfaceVariantDark = Color(0xFF383431)
val SandalOnSurfaceVariantDark = Color(0xFFD3CBC5)
val SandalTextDark = Color(0xFFE8E4E1)
val SandalErrorDark = Color(0xFFD67D80)
val SandalErrorContainerDark = Color(0xFF8C1D18)

// Nord Calm
val NordBackground = Color(0xFF2E3440)
val NordSurface = Color(0xFF3B4252)
val NordPrimary = Color(0xFF88C0D0)
val NordOnPrimary = Color(0xFF2E3440)
val NordPrimaryContainer = Color(0xFF4C566A)
val NordOnPrimaryContainer = Color(0xFFECEFF4)
val NordSecondary = Color(0xFF81A1C1)
val NordSecondaryContainer = Color(0xFF434C5E)
val NordOnSecondaryContainer = Color(0xFFD8DEE9)
val NordSurfaceVariant = Color(0xFF434C5E)
val NordOnSurfaceVariant = Color(0xFFE5E9F0)
val NordText = Color(0xFFECEFF4)
val NordError = Color(0xFFBF616A)
val NordErrorContainer = Color(0xFF7B3B44)

// Deep Ocean
val OceanBackground = Color(0xFF0F172A)
val OceanSurface = Color(0xFF1E293B)
val OceanPrimary = Color(0xFF38BDF8)
val OceanOnPrimary = Color(0xFF0F172A)
val OceanPrimaryContainer = Color(0xFF0369A1)
val OceanOnPrimaryContainer = Color(0xFFE0F2FE)
val OceanSecondary = Color(0xFF818CF8)
val OceanSecondaryContainer = Color(0xFF3730A3)
val OceanOnSecondaryContainer = Color(0xFFE0E7FF)
val OceanSurfaceVariant = Color(0xFF334155)
val OceanOnSurfaceVariant = Color(0xFFCBD5E1)
val OceanText = Color(0xFFF8FAFC)
val OceanError = Color(0xFFF87171)
val OceanErrorContainer = Color(0xFF7F1D1D)

// Warm Sunset
val SunsetBackground = Color(0xFF2D1B1E)
val SunsetSurface = Color(0xFF4A262C)
val SunsetPrimary = Color(0xFFFB923C)
val SunsetOnPrimary = Color(0xFF2D1B1E)
val SunsetPrimaryContainer = Color(0xFF9A3412)
val SunsetOnPrimaryContainer = Color(0xFFFFEDD5)
val SunsetSecondary = Color(0xFFFBBF24)
val SunsetSecondaryContainer = Color(0xFFB45309)
val SunsetOnSecondaryContainer = Color(0xFFFEF3C7)
val SunsetSurfaceVariant = Color(0xFF6B3A43)
val SunsetOnSurfaceVariant = Color(0xFFFECDD3)
val SunsetText = Color(0xFFFFF1F2)
val SunsetError = Color(0xFFF43F5E)
val SunsetErrorContainer = Color(0xFF881337)
